import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:core' as generated; // Generated by DemoPartGenerator
part 'b.g.dart'; // Generated by DemoPartGenerator

class B {
  @deprecated
  B();
}
