import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:core' as generated; // Generated by DemoPartGenerator
part 'c.g.dart'; // Generated by DemoPartGenerator

class C {
  @deprecated
  void method() {}
}
