import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:core' as generated; // Generated by DemoPartGenerator
part 'd.g.dart'; // Generated by DemoPartGenerator

class D {
  @deprecated
  int value;
}
