import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:core' as generated; // Generated by DemoPartGenerator

//import 'package:matchable_builder/matchable_builder.dart';
import 'package:matchable_builder/matchable_builder.dart';
import 'package:meta/meta.dart';

class DemoCache extends Cache {
  final List<String> classNames;

  DemoCache({
    @required this.classNames,
  });

  static DemoCache fromJson(Map<String, Object> json) {
    return DemoCache(
      classNames: List<String>.from(json["classNames"]),
    );
  }

  @override
  Map<String, dynamic> toJson() {
    return {
      "classNames": classNames,
    };
  }
}
