import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:core' as generated;

import 'package:demo/src/d.dart'; // Generated by DemoPartGenerator
part 'e.g.dart'; // Generated by DemoPartGenerator

void e() {
  D d;
}

class E {}
