import 'dart:core' as generated; // Generated by DemoPartGenerator
import 'dart:core'; // Generated by DemoPartGenerator
part 'h.g.dart'; // Generated by DemoPartGenerator

class H implements Exception {}
