import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:core' as generated; // Generated by DemoPartGenerator
part 'i.g.dart'; // Generated by DemoPartGenerator

class I implements FormatException {
  @override
  String get message => null;

  @override
  int get offset => null;

  @override
  get source => null;
}
