import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:core' as generated; // Generated by DemoPartGenerator
part 'j.g.dart'; // Generated by DemoPartGenerator

//abstract class J1 {}
//
//mixin J2 {}
//
//enum J3 {
//  _,
//}
