import 'dart:core'; // Generated by DemoPartGenerator
import 'dart:collection' as generated; // Generated by DemoPartGenerator
import 'dart:core' as generated; // Generated by DemoPartGenerator
import 'dart:convert' as generated; // Generated by DemoPartGenerator
import 'package:build/build.dart';
import 'package:demo/demo_collector.dart';
import 'package:demo/demo_combiner.dart';
import 'package:demo/demo_part_generator.dart';

Builder demoCollector(BuilderOptions ops) => DemoCollector(ops);

Builder demoCombiner(BuilderOptions ops) => DemoCombiner(ops);

Builder demoPartGenerator(BuilderOptions ops) => DemoPartGenerator(ops);
