name: matchable_builder
description: >
  Matchable builder provides a easier way to find files that you want generate code from.
version: 0.4.2
homepage: https://github.com/dart-ecosystem/matchable_builder

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.0 <0.39.0'
  build: ^1.2.2
  source_gen: ^0.9.4+6
  glob: ^1.2.0
  meta: ^1.1.8
  dart_style: ^1.3.3

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
