name: matchable_builder
description: >
  Matchable builder provides a easier way to find files that you want generate code from.
version: 0.6.0+1
homepage: https://github.com/dart-ecosystem/matchable_builder
publish_to: https://pub.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.0'
  build: ^1.3.0
  source_gen: ^0.9.5
  glob: ^1.2.0
  meta: ^1.1.8


dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
