name: matchable_builder
description: >
  Matchable builder used to build new files from existing ones.
version: 0.2.0
homepage: https://github.com/dart-ecosystem/matchable_builder
author: Copydog <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: '>=0.36.0 <0.39.0'
  build: ^1.2.2
  source_gen: ^0.9.4+6

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
